---
driver:
  name: vagrant

driver_config:
  provider: vmware_fusion
  customize:
    memory: 512

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.04

suites:
  - name: default
    run_list:
      - recipe[cooking-with-jenkins::default]
    attributes:
